name: "Hello World"
description: "Greet someone and record the time"
inputs:
  SLACK_BUILD_MONITOR_CHANNEL_ID:
    description: "Slack channel Id"
    required: true
  SLACK_BUILDBOT_TOKEN:
    description: "Slack user token"
    required: true
  SLACK_WBEHOOK_URL:
    description: "Slack incoming webhook url"
    required: true
  JOB_STATUS:
    description: "Status of your job"
    required: true
  CONTENTFUL_ENTITY_CONTENT_TYPE:
    description: "Content type of entry that changed"
    required: false
    default: ""
  CONTENTFUL_ENTITY_CONTENT:
    description: "Title of entry that changed"
    required: false
    default: ""
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "dist/index.js"
